services:
  - type: web
    name: monitor-backend
    env: node
    plan: free
    region: ohio
    rootDir: backend_node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: DATABASE_URL
        sync: false # Set via Render dashboard
      - key: Google_token
        sync: false
      - key: Qwen3_80b_token
        sync: false
      - key: gpt-oss-120b_token
        sync: false
      - key: Qwen3_4b_token
        sync: false
      - key: trinity-large-preview_token
        sync: false
      - key: Gemma3b_token
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: HUGGINGFACE_API_KEY
        sync: false
      - key: OLLAMA_API_KEY
        sync: false
      - key: OLLAMA_CLOUD_BASE_URL
        value: https://ollama.com
      - key: Gemma4_26b_token
        sync: false
      - key: Gemma4_31b_token
        sync: false
      - key: OPENROUTER_MODELS
        sync: false
      - key: OPENROUTER_SITE_URL
        value: https://my-project-2-l8ayoqad1-vsaipreethams-projects.vercel.app

  - type: web
    name: smart-job-portal
    env: python
    plan: free
    region: ohio
    rootDir: smart_job_portal
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: Gemini_token
        sync: false
      - key: DATABASE_URL
        sync: false
