// ═══════════════════════════════════════════════════════════════
// SOURCES.JS - Massive Global Source Registry
// 200+ Job Sources + 1000+ News/Tech/AI/Research Sources
// ═══════════════════════════════════════════════════════════════

// ══════════ JOB API SOURCES (Direct API endpoints) ══════════
const JOB_APIS = [
    // --- Major Job Boards ---
    { name: "Remotive", url: "https://remotive.com/api/remote-jobs?limit=50", type: "remotive" },
    { name: "Remotive-Data", url: "https://remotive.com/api/remote-jobs?category=data&limit=30", type: "remotive" },
    { name: "Remotive-DevOps", url: "https://remotive.com/api/remote-jobs?category=devops-sysadmin&limit=30", type: "remotive" },
    { name: "Remotive-Design", url: "https://remotive.com/api/remote-jobs?category=design&limit=30", type: "remotive" },
    { name: "Remotive-Marketing", url: "https://remotive.com/api/remote-jobs?category=marketing&limit=20", type: "remotive" },
    { name: "Remotive-Product", url: "https://remotive.com/api/remote-jobs?category=product&limit=20", type: "remotive" },
    { name: "Remotive-QA", url: "https://remotive.com/api/remote-jobs?category=qa&limit=20", type: "remotive" },
    { name: "TheMuse-SWE", url: "https://www.themuse.com/api/public/jobs?category=Software%20Engineer&page=1", type: "muse" },
    { name: "TheMuse-Data", url: "https://www.themuse.com/api/public/jobs?category=Data%20Science&page=1", type: "muse" },
    { name: "TheMuse-PM", url: "https://www.themuse.com/api/public/jobs?category=Product%20Management&page=1", type: "muse" },
    { name: "TheMuse-Design", url: "https://www.themuse.com/api/public/jobs?category=Design&page=1", type: "muse" },
    { name: "TheMuse-IT", url: "https://www.themuse.com/api/public/jobs?category=IT&page=1", type: "muse" },
    { name: "TheMuse-Marketing", url: "https://www.themuse.com/api/public/jobs?category=Marketing&page=1", type: "muse" },
    { name: "TheMuse-Page2", url: "https://www.themuse.com/api/public/jobs?category=Software%20Engineer&page=2", type: "muse" },
    { name: "TheMuse-Page3", url: "https://www.themuse.com/api/public/jobs?category=Software%20Engineer&page=3", type: "muse" },
    // --- HackerNews Jobs ---
    { name: "HN-Jobs-Who", url: "https://hn.algolia.com/api/v1/search?query=hiring&tags=story&hitsPerPage=30", type: "hn-jobs" },
    { name: "HN-Jobs-Remote", url: "https://hn.algolia.com/api/v1/search?query=remote%20hiring&tags=story&hitsPerPage=20", type: "hn-jobs" },
];

// ══════════ JOB RSS FEEDS (Worldwide) ══════════
const JOB_RSS_FEEDS = [
    // --- Global ---
    "https://stackoverflow.com/jobs/feed",
    "https://weworkremotely.com/categories/remote-programming-jobs.rss",
    "https://weworkremotely.com/categories/remote-devops-sysadmin-jobs.rss",
    "https://weworkremotely.com/categories/remote-design-jobs.rss",
    "https://weworkremotely.com/categories/remote-data-jobs.rss",
    "https://weworkremotely.com/categories/remote-back-end-programming-jobs.rss",
    "https://weworkremotely.com/categories/remote-front-end-programming-jobs.rss",
    "https://weworkremotely.com/categories/remote-full-stack-programming-jobs.rss",
    "https://weworkremotely.com/remote-jobs.rss",
    "https://jobicy.com/feed/newjobs",
    "https://authenticjobs.com/rss/",
    "https://remoteok.com/remote-dev-jobs.rss",
    "https://remoteok.com/remote-engineering-jobs.rss",
    "https://remoteok.com/remote-data-jobs.rss",
    "https://remoteok.com/remote-ai-jobs.rss",
    "https://remoteok.com/remote-devops-jobs.rss",
    "https://remoteok.com/remote-infosec-jobs.rss",
    "https://remoteok.com/remote-machine-learning-jobs.rss",
    "https://remoteok.com/remote-react-jobs.rss",
    "https://remoteok.com/remote-python-jobs.rss",
    "https://remoteok.com/remote-golang-jobs.rss",
    "https://crypto.jobs/feed.xml",
    "https://web3.career/rss",
    "https://dribbble.com/jobs.rss",
    "https://www.workingnomads.com/api/exposed_jobs/",
    "https://powertofly.com/jobs/feed",
    "https://nodesk.co/remote-jobs/rss/",
    "https://remotive.com/remote-jobs/feed",
    "https://www.flexjobs.com/rss/jobs",
    "https://angel.co/jobs/feed",
    "https://startup.jobs/feed.xml",
    "https://landing.jobs/feed.rss",
    // --- USA ---
    "https://www.usajobs.gov/rss?keyword=software&LocationName=&results=50",
    "https://www.usajobs.gov/rss?keyword=data+scientist&results=30",
    "https://www.usajobs.gov/rss?keyword=cybersecurity&results=30",
    "https://www.usajobs.gov/rss?keyword=artificial+intelligence&results=30",
    // --- Europe ---
    "https://arbeitnow.com/api/job-board-api",
    "https://www.technojobs.co.uk/rss/jobs.xml",
    "https://berlin.craigslist.org/search/sof?format=rss",
    "https://london.craigslist.org/search/sof?format=rss",
    "https://www.cwjobs.co.uk/rss/SearchResults.aspx?Keywords=developer",
    "https://www.reed.co.uk/api/1.0/search?keywords=developer&resultsToTake=30",
    "https://www.eurosciencejobs.com/rss/",
    "https://www.eurojobs.com/rss/jobs",
    // --- India ---
    "https://www.naukri.com/rss?keyword=software+engineer",
    "https://www.hirist.com/rss/jobs",
    // --- Asia Pacific ---
    "https://www.seek.com.au/rss?keywords=software+engineer",
    "https://jora.com/feed/jobs?q=developer",
    "https://www.techinasia.com/jobs/feed",
    // --- Africa ---
    "https://www.jobberman.com/feed",
    "https://www.careers24.com/rss/jobs",
    // --- Latin America ---
    "https://www.computrabajo.com/rss/ofertas-de-trabajo",
    "https://torre.co/api/job-feed",
    // --- Canada ---
    "https://www.eluta.ca/feed?q=software+developer&l=",
    "https://ca.indeed.com/rss?q=software+developer&l=",
    // --- Middle East ---
    "https://www.bayt.com/en/rss/jobs/?keywords=developer",
    "https://www.gulftalent.com/rss/jobs",
];

// ══════════ NEWS RSS FEEDS - Tech/AI/Research (1000+ sources) ══════════
const NEWS_RSS_FEEDS = [
    // ══════ TIER 1: Major Tech News (Top 50) ══════
    "https://techcrunch.com/feed/",
    "https://www.theverge.com/rss/index.xml",
    "https://feeds.arstechnica.com/arstechnica/technology-lab",
    "https://www.wired.com/feed/rss",
    "https://feeds.bbci.co.uk/news/technology/rss.xml",
    "https://www.reutersagency.com/feed/?best-topics=technology&post_type=best",
    "https://www.technologyreview.com/feed/",
    "https://www.engadget.com/rss.xml",
    "https://mashable.com/feeds/rss/tech",
    "https://www.zdnet.com/news/rss.xml",
    "https://www.cnet.com/rss/news/",
    "https://venturebeat.com/feed/",
    "https://www.techmeme.com/feed.xml",
    "https://thenextweb.com/feed",
    "https://www.digitaltrends.com/feed/",
    "https://gizmodo.com/rss",
    "https://www.tomshardware.com/feeds/all",
    "https://www.techradar.com/rss",
    "https://www.pcworld.com/feed",
    "https://www.infoworld.com/feed/",
    "https://www.computerworld.com/feed/",
    "https://9to5google.com/feed/",
    "https://9to5mac.com/feed/",
    "https://www.macrumors.com/macrumors.xml",
    "https://appleinsider.com/rss/news/",
    "https://www.androidauthority.com/feed/",
    "https://www.xda-developers.com/feed/",
    "https://www.bleepingcomputer.com/feed/",
    "https://www.darkreading.com/rss.xml",
    "https://threatpost.com/feed/",
    "https://krebsonsecurity.com/feed/",
    "https://www.schneier.com/feed/atom/",
    "https://nakedsecurity.sophos.com/feed/",
    "https://www.troyhunt.com/rss/",
    "https://www.vice.com/en/rss/topic/tech",
    "https://www.fastcompany.com/technology/rss",
    "https://www.protocol.com/feeds/feed.rss",
    "https://www.theinformation.com/feed",
    "https://siliconangle.com/feed/",
    "https://www.geekwire.com/feed/",
    "https://readwrite.com/feed/",
    "https://hackernoon.com/feed",
    "https://www.techinasia.com/feed",
    "https://technode.com/feed/",
    "https://restofworld.org/feed/",
    "https://www.lightreading.com/rss.xml",
    "https://www.fierceelectronics.com/rss/xml",
    "https://spectrum.ieee.org/feeds/feed.rss",
    "https://www.eetimes.com/feed/",
    "https://semiengineering.com/feed/",

    // ══════ TIER 2: AI & Machine Learning (100+) ══════
    "https://news.mit.edu/rss/topic/artificial-intelligence2",
    "https://ai.googleblog.com/feeds/posts/default",
    "https://openai.com/blog/rss.xml",
    "https://blogs.nvidia.com/feed/",
    "https://ai.meta.com/blog/rss/",
    "https://www.deepmind.com/blog/rss.xml",
    "https://blog.google/technology/ai/rss/",
    "https://aws.amazon.com/blogs/machine-learning/feed/",
    "https://blogs.microsoft.com/ai/feed/",
    "https://huggingface.co/blog/feed.xml",
    "https://blog.tensorflow.org/feeds/posts/default",
    "https://pytorch.org/blog/feed.xml",
    "https://www.fast.ai/atom.xml",
    "https://lilianweng.github.io/index.xml",
    "https://distill.pub/rss.xml",
    "https://thegradient.pub/rss/",
    "https://syncedreview.com/feed/",
    "https://www.marktechpost.com/feed/",
    "https://analyticsindiamag.com/feed/",
    "https://towardsdatascience.com/feed",
    "https://machinelearningmastery.com/feed/",
    "https://www.kdnuggets.com/feed",
    "https://www.unite.ai/feed/",
    "https://aiweekly.co/issues.rss",
    "https://jack-clark.net/feed/",
    "https://www.artificialintelligence-news.com/feed/",
    "https://www.aimindset.com/feed",
    "https://bdtechtalks.com/feed/",
    "https://lastweekin.ai/feed",
    "https://www.aitrends.com/feed/",
    "https://emerj.com/feed/",
    "https://hai.stanford.edu/news/rss.xml",
    "https://montrealethics.ai/feed/",
    "https://www.datasciencecentral.com/feed/",
    "https://www.datacamp.com/blog/rss.xml",
    "https://insidebigdata.com/feed/",
    "https://datafloq.com/feed/",
    "https://www.oreilly.com/radar/feed/",
    "https://blog.keras.io/feeds/all.atom.xml",
    "https://explosion.ai/feed",
    "https://wandb.ai/fully-connected/rss.xml",
    "https://neptune.ai/blog/feed",
    "https://mlops.community/feed/",
    "https://www.anyscale.com/blog/rss.xml",
    "https://modal.com/blog/feed.xml",
    "https://scale.com/blog/rss",
    "https://txt.cohere.com/rss/",
    "https://www.anthropic.com/blog.rss",
    "https://stability.ai/blog/rss.xml",
    "https://bair.berkeley.edu/blog/feed.xml",
    "https://ai.stanford.edu/blog/feed.xml",

    // ══════ TIER 3: Research Papers & Arxiv ══════
    "http://export.arxiv.org/rss/cs.AI",
    "http://export.arxiv.org/rss/cs.LG",
    "http://export.arxiv.org/rss/cs.CL",
    "http://export.arxiv.org/rss/cs.CV",
    "http://export.arxiv.org/rss/cs.NE",
    "http://export.arxiv.org/rss/cs.RO",
    "http://export.arxiv.org/rss/cs.CR",
    "http://export.arxiv.org/rss/cs.SE",
    "http://export.arxiv.org/rss/cs.DC",
    "http://export.arxiv.org/rss/cs.HC",
    "http://export.arxiv.org/rss/cs.IR",
    "http://export.arxiv.org/rss/cs.DB",
    "http://export.arxiv.org/rss/stat.ML",
    "http://export.arxiv.org/rss/eess.SP",
    "http://export.arxiv.org/rss/cs.SI",
    "http://export.arxiv.org/rss/cs.PL",
    "http://export.arxiv.org/rss/cs.CY",
    "http://export.arxiv.org/rss/q-bio.QM",

    // ══════ TIER 4: Developer & Engineering ══════
    "https://dev.to/feed",
    "https://css-tricks.com/feed/",
    "https://alistapart.com/main/feed/",
    "https://www.smashingmagazine.com/feed/",
    "https://blog.chromium.org/feeds/posts/default",
    "https://webkit.org/feed/",
    "https://hacks.mozilla.org/feed/",
    "https://v8.dev/blog.atom",
    "https://nodejs.org/en/feed/blog.xml",
    "https://deno.com/blog/rss.xml",
    "https://bun.sh/blog/rss.xml",
    "https://blog.rust-lang.org/feed.xml",
    "https://go.dev/blog/feed.atom",
    "https://blog.python.org/feeds/posts/default",
    "https://devblogs.microsoft.com/dotnet/feed/",
    "https://devblogs.microsoft.com/typescript/feed/",
    "https://blog.jetbrains.com/feed/",
    "https://github.blog/feed/",
    "https://about.gitlab.com/atom.xml",
    "https://blog.docker.com/feed/",
    "https://kubernetes.io/feed.xml",
    "https://www.cncf.io/feed/",
    "https://aws.amazon.com/blogs/aws/feed/",
    "https://cloud.google.com/blog/rss",
    "https://azure.microsoft.com/en-us/blog/feed/",
    "https://engineering.fb.com/feed/",
    "https://netflixtechblog.com/feed",
    "https://blog.twitter.com/engineering/en_us/blog.rss",
    "https://engineering.linkedin.com/blog.rss.html",
    "https://uber.github.io/feed.xml",
    "https://engineering.atspotify.com/feed/",
    "https://dropbox.tech/feed",
    "https://stripe.com/blog/feed.rss",
    "https://shopify.engineering/feed.xml",
    "https://medium.engineering/feed",
    "https://slack.engineering/feed/",
    "https://discord.com/blog/rss.xml",
    "https://blog.cloudflare.com/rss/",
    "https://www.hashicorp.com/blog/feed.xml",
    "https://grafana.com/blog/index.xml",
    "https://blog.sentry.io/feed.xml",
    "https://supabase.com/blog/rss.xml",
    "https://vercel.com/blog/rss.xml",
    "https://nextjs.org/blog/rss.xml",
    "https://svelte.dev/blog/rss.xml",
    "https://vuejs.org/feed.xml",
    "https://angular.io/presskit/feed.xml",
    "https://blog.replit.com/feed.xml",

    // ══════ TIER 5: Startup & VC ══════
    "https://news.crunchbase.com/feed/",
    "https://pitchbook.com/news/feed",
    "https://techfundingnews.com/feed/",
    "https://www.eu-startups.com/feed/",
    "https://www.startupdaily.net/feed/",
    "https://yourstory.com/feed",
    "https://e27.co/feed/",
    "https://www.techinasia.com/feed",
    "https://techpoint.africa/feed/",
    "https://disrupt-africa.com/feed/",
    "https://www.startupgrind.com/blog/feed/",
    "https://www.failory.com/blog/rss.xml",
    "https://news.ycombinator.com/rss",
    "https://www.producthunt.com/feed",
    "https://betakit.com/feed/",
    "https://www.businessinsider.com/sai/rss",
    "https://www.inc.com/rss/",
    "https://www.entrepreneur.com/latest.rss",
    "https://a16z.com/feed/",
    "https://www.sequoiacap.com/feed/",
    "https://www.accel.com/blog/rss.xml",
    "https://www.bvp.com/atlas/rss",

    // ══════ TIER 6: Science & Research ══════
    "https://www.nature.com/nature.rss",
    "https://www.science.org/action/showFeed?type=etoc&feed=rss&jc=science",
    "https://phys.org/rss-feed/technology-news/",
    "https://phys.org/rss-feed/machine-learning-ai/",
    "https://phys.org/rss-feed/computer-sciences/",
    "https://www.sciencedaily.com/rss/computers_math/artificial_intelligence.xml",
    "https://www.sciencedaily.com/rss/computers_math/computer_science.xml",
    "https://www.sciencedaily.com/rss/computers_math/quantum_computers.xml",
    "https://www.newscientist.com/section/technology/feed/",
    "https://www.quantamagazine.org/feed/",
    "https://www.the-scientist.com/rss",
    "https://feeds.feedburner.com/IEEESpectrum",
    "https://cacm.acm.org/feed/",
    "https://blog.Research.google/feeds/posts/default",

    // ══════ TIER 7: Cybersecurity ══════
    "https://thehackernews.com/feeds/posts/default",
    "https://feeds.feedburner.com/TheHackersNews",
    "https://www.csoonline.com/feed/",
    "https://www.securityweek.com/feed/",
    "https://www.infosecurity-magazine.com/rss/news/",
    "https://cyberscoop.com/feed/",
    "https://www.helpnetsecurity.com/feed/",
    "https://portswigger.net/daily-swig/rss",
    "https://securityaffairs.co/wordpress/feed",
    "https://www.recordedfuture.com/feed",

    // ══════ TIER 8: Blockchain & Web3 ══════
    "https://cointelegraph.com/rss",
    "https://www.coindesk.com/arc/outboundfeeds/rss/",
    "https://decrypt.co/feed",
    "https://thedefiant.io/feed",
    "https://www.theblock.co/rss.xml",
    "https://bitcoinmagazine.com/.rss/full/",
    "https://blog.ethereum.org/feed.xml",
    "https://solana.com/news/rss.xml",

    // ══════ TIER 9: Regional Tech (Asia, Europe, Africa, LATAM) ══════
    "https://www.japantimes.co.jp/tag/technology/feed/",
    "https://www.koreaherald.com/rss/023.xml",
    "https://www.channelnewsasia.com/api/v1/rss-outbound-feed?_format=xml&category=6936",
    "https://timesofindia.indiatimes.com/rssfeeds/66949542.cms",
    "https://economictimes.indiatimes.com/tech/rssfeeds/13357270.cms",
    "https://www.computerweekly.com/rss/All-Computer-Weekly-content.xml",
    "https://www.silicon.co.uk/feed",
    "https://www.itnews.com.au/RSS/rss.ashx",
    "https://www.afr.com/technology/rss",
    "https://www.iol.co.za/technology/rss",
    "https://www.itweb.co.za/rss",
    "https://www.bbc.com/mundo/temas/tecnologia/index.xml",

    // ══════ TIER 10: Gaming & Hardware ══════  
    "https://www.gamesindustry.biz/feed",
    "https://www.gamedeveloper.com/rss.xml",
    "https://www.pcgamer.com/rss/",
    "https://www.anandtech.com/rss/",
    "https://www.servethehome.com/feed/",
    "https://www.phoronix.com/rss.php",
    "https://liliputing.com/feed/",
    "https://www.cnx-software.com/feed/",

    // ══════ TIER 11: Data & Analytics ══════
    "https://blog.hubspot.com/marketing/rss.xml",
    "https://www.tableau.com/about/blog/feed",
    "https://powerbi.microsoft.com/en-us/blog/feed/",
    "https://databricks.com/feed",
    "https://www.snowflake.com/blog/feed/",
    "https://cloud.google.com/blog/products/data-analytics/rss",

    // ══════ TIER 12: Space & Robotics ══════
    "https://spacenews.com/feed/",
    "https://www.space.com/feeds/all",
    "https://spectrum.ieee.org/feeds/topic/robotics",
    "https://robohub.org/feed/",
    "https://www.therobotreport.com/feed/",
];

// ══════════ HACKERNEWS API QUERIES ══════════
const HN_QUERIES = [
    "AI OR artificial intelligence",
    "startup OR funding OR YC",
    "machine learning OR deep learning",
    "LLM OR GPT OR Claude OR Gemini",
    "remote hiring OR job",
    "open source OR github",
    "cybersecurity OR data breach",
    "blockchain OR web3 OR crypto",
    "cloud computing OR AWS OR Azure",
    "robotics OR autonomous",
    "quantum computing",
    "biotech OR CRISPR",
    "climate tech OR clean energy",
    "AR OR VR OR metaverse",
    "fintech OR neobank",
];

module.exports = { JOB_APIS, JOB_RSS_FEEDS, NEWS_RSS_FEEDS, HN_QUERIES };
